- name: install mysql-server
  apt: pkg=mysql-server state=installed update_cache=yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - mysql

- name: install libmysqlclient
  apt: pkg=libmysqlclient-dev
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - mysql
- name: install python-mysqldb
  apt: pkg=python-mysqldb
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - mysql

- name: change root password for mysql
  mysql_user: name=root
              password={{ mysql_root_pass }}
              host={{ item }}
              state=present
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  tags:
    - mysql

- name: copy root file creds to remote
  copy: src=creds dest=~/.my.cnf
  tags:
    - mysql

- name: delete anonymous mysql users
  mysql_user: login_user=root
              login_password={{ mysql_root_pass }}
              name=''
              host={{ item }}
              state=absent
  with_items:
    - localhost
    - $inventory_hostname
  tags:
    - mysql

- name: remove test database
  mysql_db: name=test state=absent
  tags:
    - mysql

- name: add mysql user
  mysql_user: login_user=root
              login_password={{ mysql_root_pass }}
              name={{ mysql_user }}
              password={{ mysql_pass }}
              host={{ item }}
              priv=*.*:ALL 
              state=present
  with_items:
    - 198.199.93.240
    - localhost
    - 192.168.111.1
  tags:
    - mysql

- name: create mysql database
  mysql_db: login_user={{ mysql_user }}
            login_password={{ mysql_pass }}
            name={{ mysql_db }}
            state=present
  register: database_created
  tags:
    - mysql

- name: copy mysql database file
  copy: src=db.sql dest=~/db.sql
  tags:
    - mysql

- name: import mysql database
  mysql_db: login_user={{ mysql_user }}
            login_password={{ mysql_pass }}
            name={{ mysql_db }}
            state=import
            target=~/db.sql
  tags:
    - mysql

- name: allow remote login to mysql
  lineinfile: dest=/etc/mysql/my.cnf
              regexp=^bind-address
              line=bind-address=0.0.0.0
  notify: 
  - restart mysql
  tags:
    - mysql
